DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS profiles;

CREATE TABLE user(
	userID INTEGER PRIMARY KEY,
	fname VARCHAR(55) NOT NULL,
	lname VARCHAR(55) NOT NULL,
	username VARCHAR(55) NOT NULL,
	pwd VARCHAR(55) NOT NULL,
	email VARCHAR(55) NOT NULL
);

CREATE TABLE profiles(
	profiles_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	profile_intro TEXT NOT NULL,
	profile_about TEXT NOT NULL,
	userID INTEGER,
	FOREIGN KEY (userID) REFERENCES user(userID)
);
